config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles, only: [:index, :show]
  namespace :admin do
    match '/', to: 'dashboards#index', via: :get
    resources :articles
    resources :users
    resources :dashboards, only: [:index]
    resources :useful_links
  end
  root :to => 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :slug
  paginates_per 10

  belongs_to :user
  has_and_belongs_to_many :tags

  # attribute :comma_separated_tags, :string

  # def comma_separated_tags
  #   self.tags.pluck(:name)*','
  # end

end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_and_belongs_to_many :articles
end

app/models/useful_link.rb
class UsefulLink < ApplicationRecord
  validates :description, :url, presence: true

  paginates_per 15

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    base: 1,
    admin: 5
  }

end

app/controllers/admin/admin_conrtoller.rb
class ArticlesController < ActionController::Base

  before_action :set_article

  def index
    @articles = Article.all
  end

  def show
    #@article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to article_path, notice: "Article has been created"
    else
      render :new
    end
  end

  def edit
    #@article = Article.find(params[:id])
  end

  def delete
    #@article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to article_path, notice: "Model successfully updated."
    else
      render :edit
    end
  end

  def update
    #@article = Article.find(params[:id])
    if @article.destroy
      redirect_to article_path, notice: "Model successfully deleted."
    else
      redirect_to article_path, notice: "Not possible to destroy the Model."
    end
  end

  private

  def set_book
    #@article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

  def index
    load_articles
  end

  def show
    load_article
    decorate_article
  end

  def new
    build_article
  end

  def create
    build_article
    create_article or render :new
  end

  def edit
    load_article
  end

  def update
    load_article
    update_article or render :edit
  end

  def destroy
    load_article
    destroy_article
  end

  private

  def destroy_article
    @article.destroy
    redirect_to admin_articles_path, notice: "Article successfully deleted."
  end

  def create_article
    return false unless @article.valid?
    result = CreateArticle.new(attributes: article_params).call
    if result.success?
      redirect_to admin_article_path(result.article)
    else
      false
    end
  end

  def update_article
    result = UpdateArticle.new(attributes: article_params, article: @article).call
    if result.success?
      redirect_to admin_article_path(result.article)
    else
      false
    end
  end

  def build_article
    # @article = Article.new(article_params)
    @article = ArticleFormModel.new(article_params)
  end

  def load_articles
    @q = Article.ransack(params[:q])
    @articles = @q.result.page(params[:page])
  end

  def load_article
    @article = Article.find(params[:id])
  end

  def article_params
    return {} unless params[:article]

    params.require(:article)
      .permit(:title, :description, :published, :comma_separated_tags)
      # .merge(user: current_user)
  end

  def decorate_article
    @article = Admin::ArticleDecorator.decorate(@article)
  end

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  def index
  end
end

app/controllers/admin/useful_links_controller.rb
class Admin::UsefulLinksController < AdminController

  def index
    load_useful_links
  end

  def show
    load_useful_link
  end

  def new
    build_useful_link
  end

  def create
    build_useful_link
    create_useful_link or render :new
  end

  def edit
    load_useful_link
  end

  def update
    load_useful_link
    update_useful_link or render :edit
  end

  def destroy
    load_useful_link
    destroy_useful_link
  end

  private

  def destroy_useful_link
    @useful_link.destroy
    redirect_to admin_useful_links_path, notice: "UsefulLink successfully deleted."
  end

  def create_useful_link
    @useful_link = UsefulLink.new(useful_link_params)
    if @useful_link.save
      redirect_to admin_useful_links_path, notice: "UsefulLink has been created"
    else
      render :new
    end
  end

  def update_useful_link
    if @useful_link.update_attributes(useful_link_params)
      redirect_to admin_useful_link_path, notice: "useful_link successfully updated."
    else
      false
    end
  end

  def build_useful_link
    @useful_link = UsefulLink.new(useful_link_params)
  end

  def load_useful_links
    @useful_links = UsefulLink.all.page(params[:page])
  end

  def load_useful_link
    @useful_link = UsefulLink.find(params[:id])
  end

  def useful_link_params
    return {} unless params[:useful_link]

    params.require(:useful_link)
      .permit(:url, :description, :processed)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    load_users
  end

  def show
    load_user
  end

  def edit
    load_user
  end

  def update
    load_user
    update_user or render :edit
  end

  def destroy
    load_user
    destroy_user
  end

  private

  def destroy_user
    @user.destroy
    redirect_to admin_users_path, notice: "user successfully deleted."
  end

  def update_user
    if @user.update_attributes(user_params)
      redirect_to admin_user_path, notice: "user successfully updated."
    else
      false
    end
  end

  def load_users
    @users = User.all
  end

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    return {} unless params[:user]

    params.require(:user)
      .permit(:first_name, :last_name)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_user_role

  private

  def check_user_role
    unless current_user and current_user.admin?
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    load_articles
  end

  def show
    load_article
    decorate_article
  end

  private

  def load_article
    @article = Article.friendly.find(params[:id])
  end

  def load_articles
    @q = Article.ransack(params[:q])
    @articles = @q.result.page(params[:page])
  end

  def decorate_article
    @article = ArticleDecorator.decorate(@article)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include MarkdownHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
 require 'redcarpet'
 require 'rouge'
 require 'rouge/plugins/redcarpet'

 class HTML < Redcarpet::Render::HTML
   include Rouge::Plugins::Redcarpet
 end

 def markdown(text)
   render_options = {
     # filer_html: true,
     hard_wrap: true,
     link_attributes: { rel: 'nofollow' },
     prettify: true
   }
   renderer = HTML.new(render_options)
   extras = {
     autolink: true,
     no_intra_emphasis: true,
     disable_indented_code_blocks: true,
     fenced_code_blocks: true,
     strikethrough: true,
     superscript: true,
     lax_spacing: true
   }

 markdown = Redcarpet::Markdown.new(renderer, extras)
   raw markdown.render(text)
 end

end

app/views/admin/articles/_form.slim
= f.input :title
= f.input :description
= f.input :published
= f.input :comma_separated_tags

app/views/admin/articles/edit.slim
h1 Edit Article Detail
= simple_form_for [:admin, @article] do |f|
  = render 'form', f: f
  = f.button :submit
= link_to 'Back', admin_article_path(@article)

app/views/admin/articles/index.slim
= search_form_for @q, url: admin_articles_path do |f|
  - f.label :title
  - f.search_field :title_cont


- if @articles.blank?
  p
    | No articles yet
- else
  ul#articles
    - @articles.each do |article|
      li= link_to article.title, admin_article_path(article)
= link_to 'New', new_admin_article_path(@articles)
= paginate @articles

app/views/admin/articles/new.slim
h1 Add New Article
= simple_form_for [:admin, @article], url: admin_articles_path do |f|
  = render 'form', f: f
  = f.button :submit

app/views/admin/articles/show.slim
= @article.title
= @article.status
br/
= @article.comma_separated_tags
br/
= markdown(@article.description)
br/
= link_to 'Edit', edit_admin_article_path(@article)
br/
= link_to 'Back', admin_articles_path
br/
= link_to 'Delete', admin_article_path(@article), method: :delete,
                                                  data: {confirm: "Are you sure?"}

app/views/admin/dashboards/index.slim
= link_to 'Users', admin_users_path
br/
= link_to 'Articles', admin_articles_path

app/views/admin/index.slim
admin
- if @articles.blank?
  p
    | No articles yet
- else
  ul#articles
    - @articles.each do |article|
      li= link_to article.title, article_path(article)

app/views/admin/show.slim
admin
= @article.title
br/
= @article.description

app/views/admin/useful_links/_form.slim
= f.input :url
= f.input :description
= f.input :processed

app/views/admin/useful_links/edit.slim
h1 Edit UsefulLink Detail
= simple_form_for [:admin, @useful_link] do |f|
  = render 'form', f: f
  = f.button :submit
= link_to 'Back', admin_useful_link_path(@useful_link)

app/views/admin/useful_links/index.slim
- if @useful_links.blank?
  p
    | No useful_links yet
- else
  ul#useful_links
    - @useful_links.each do |useful_link|
      li= link_to useful_link.url, admin_useful_link_path(useful_link)
= link_to 'New', new_admin_useful_link_path(@useful_links)
= paginate @useful_links

app/views/admin/useful_links/new.slim
h1 Add New UsefulLink
= simple_form_for [:admin, @useful_link] do |f|
  = render 'form', f: f
  = f.button :submit

app/views/admin/useful_links/show.slim
= @useful_link.url
br/
= @useful_link.description
br/
= link_to 'Edit', edit_admin_useful_link_path(@useful_link)
br/
= link_to 'Back', admin_useful_links_path
br/
= link_to 'Delete', admin_useful_link_path(@useful_link), method: :delete,
                                                  data: {confirm: "Are you sure?"}

app/views/admin/users/_form.slim
= f.input :first_name
= f.input :last_name

app/views/admin/users/edit.slim
h1 Edit user Detail
= simple_form_for [:admin, @user] do |f|
  = render 'form', f: f
  = f.button :submit
= link_to 'Back', admin_user_path(@user)

app/views/admin/users/index.slim
- if @users.blank?
  p
    | No users yet
- else
  ul#users
    - @users.each do |user|
      li= link_to user.email, admin_user_path(user)

app/views/admin/users/show.slim
= @user.email
br/
= @user.first_name
br/
= @user.last_name
br/
= link_to 'Edit', edit_admin_user_path(@user)
br/
= link_to 'Back', admin_users_path
br/
= link_to 'Delete', admin_user_path(@user), method: :delete,
                                                  data: {confirm: "Are you sure?"}

app/views/articles/index.slim
= search_form_for @q, url: articles_path do |f|
  - f.label :title
  - f.search_field :title_cont


- if @articles.blank?
  p
    | No articles yet
- else
  ul#articles
    - @articles.each do |article|
      li= link_to article.title, article_path(article)
= paginate @articles

app/views/articles/show.slim
h1= @article.title
p= @article.author_name
br/
= markdown(@article.description)
ul#articles
  - @article.tags.each do |tag|
   li= tag.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>